# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_decision_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='accepted',
            field=models.NullBooleanField(default=None),
        ),
    ]
