# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-24 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171118_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weight',
            name='criteria',
        ),
        migrations.RemoveField(
            model_name='weight',
            name='user',
        ),
        migrations.AddField(
            model_name='criteria',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Weight',
        ),
    ]
